name: Generate Snake

on:
  push:
    branches:
      - master  # or main if that's your default branch
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
